version: 2
jobs:
  nginx:
    machine: true
    steps:
      - checkout
      - run: cd nginx && docker build -t base:nginx ./
  shadowsocks:
    machine: true
    steps:
      - checkout
      - run: cd shadowsocks && docker build -t base:shadowsocks ./
  v2ray:
    machine: true
    steps:
      - checkout
      - run: cd v2ray && docker build -t base:v2ray ./

workflows:
  version: 2
  all:
    jobs:
      - nginx
      - shadowsocks
      - v2ray
