version: 2
jobs:
  nginx:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          cd nginx && docker build -t ahxxm/base:nginx ./
          docker push ahxxm/base:nginx
  shadowsocks:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          cd shadowsocks && docker build -t ahxxm/base:shadowsocks ./
          docker push ahxxm/base:shadowsocks
  v2ray:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          cd v2ray && docker build -t ahxxm/base:v2ray ./
          docker push ahxxm/base:v2ray

workflows:
  version: 2
  commit:
    jobs:
      - nginx
      - shadowsocks
      - v2ray
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master
    jobs:
      - nginx
      - shadowsocks
      - v2ray
