version: 2.1
commands:
  build_push:
    parameters:
      tag:
        default: "invalid"
        type: string
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          cd <<parameters.tag>> && docker build -t ahxxm/base:<<parameters.tag>> ./
          docker push ahxxm/base:<<parameters.tag>>
jobs:
  nginx:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - build_push:
          tag: "nginx"
  qbittorrent:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - build_push:
          tag: "qbittorrent"
  fo:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - build_push:
          tag: "fo"
  shadowsocks:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - build_push:
          tag: "shadowsocks"

workflows:
  version: 2
  commit:
    jobs:
      - nginx
      - shadowsocks
      - qbittorrent
