version: 2.1
commands:
  build_push:
    parameters:
      tag:
        default: "invalid"
        type: string
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          cd <<parameters.tag>> && docker build -t ahxxm/base:<<parameters.tag>> ./
          docker push ahxxm/base:<<parameters.tag>>
jobs:
  nginx:
    machine: true
    steps:
      - build_push:
          tag: "nginx"
  qbittorrent:
    machine: true
    steps:
      - build_push:
          tag: "qbittorrent"
  shadowsocks:
    machine: true
    steps:
      - build_push:
          tag: "shadowsocks"
  v2ray:
    machine: true
    steps:
      - build_push:
          tag: "v2ray"

workflows:
  version: 2
  commit:
    jobs:
      - nginx
      - shadowsocks
      - v2ray
      - qbittorrent
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 16 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master
    jobs:
      - nginx
      - shadowsocks
      - v2ray
